#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _APCounter2_reg();
extern void _ar_traub_reg();
extern void _beforestep_py_reg();
extern void _CA1ika_reg();
extern void _CA1ikdr_reg();
extern void _CA1ina_reg();
extern void _cad_reg();
extern void _cadad_reg();
extern void _cadecay_destexhe_reg();
extern void _cadyn_reg();
extern void _Cadynamics_reg();
extern void _cagk_reg();
extern void _cal_mh_reg();
extern void _cal_mig_reg();
extern void _can_mig_reg();
extern void _cancr_reg();
extern void _canin_reg();
extern void _caolmw_reg();
extern void _capr_reg();
extern void _cat_mig_reg();
extern void _cat_traub_reg();
extern void _catcb_reg();
extern void _ch_CavL_reg();
extern void _ch_CavN_reg();
extern void _ch_KCaS_reg();
extern void _ch_Kdrfastngf_reg();
extern void _ch_KvAngf_reg();
extern void _ch_KvCaB_reg();
extern void _ch_leak_reg();
extern void _ch_Navngf_reg();
extern void _cp_reg();
extern void _cp2_reg();
extern void _DynamicNetStim_reg();
extern void _gabab_reg();
extern void _h_BS_reg();
extern void _h_harnett_reg();
extern void _h_kole_reg();
extern void _h_migliore_reg();
extern void _HH_traub_reg();
extern void _HH2_reg();
extern void _hin_reg();
extern void _htc_reg();
extern void _Iahp_reg();
extern void _IC_reg();
extern void _ICal_reg();
extern void _Ican_reg();
extern void _ican_sidi_reg();
extern void _icaolmw_reg();
extern void _icapr_reg();
extern void _iccr_reg();
extern void _iconc_Ca_reg();
extern void _iholmkop_reg();
extern void _iholmw_reg();
extern void _ihpyrkop_reg();
extern void _IKM_reg();
extern void _ikscr_reg();
extern void _IKsin_reg();
extern void _IL_reg();
extern void _IL_gutnick_reg();
extern void _IM_cortex_reg();
extern void _ipulse3_reg();
extern void _IT_reg();
extern void _IT2_reg();
extern void _kahppr_reg();
extern void _kaolmkop_reg();
extern void _kap_BS_reg();
extern void _kapcb_reg();
extern void _kapin_reg();
extern void _kapyrkop_reg();
extern void _kBK_reg();
extern void _kca_reg();
extern void _kcaolmw_reg();
extern void _kcpr_reg();
extern void _kctin_reg();
extern void _kdmc_BS_reg();
extern void _kdr_BS_reg();
extern void _kdr2_orig_reg();
extern void _kdrbwb_reg();
extern void _kdrcr_reg();
extern void _kdrin_reg();
extern void _kdrolmkop_reg();
extern void _kdrpr_reg();
extern void _kdrpyrkop_reg();
extern void _kl_reg();
extern void _km_reg();
extern void _kv_reg();
extern void _my_exp2syn_reg();
extern void _MyExp2SynAlpha_reg();
extern void _MyExp2SynBB_reg();
extern void _MyExp2SynNMDABB_reg();
extern void _na_2_reg();
extern void _naf2_reg();
extern void _nafbwb_reg();
extern void _nafcr_reg();
extern void _nafolmkop_reg();
extern void _nafpr_reg();
extern void _nafpyrkop_reg();
extern void _nafx_reg();
extern void _nap_sidi_reg();
extern void _nax_BS_reg();
extern void _naz_reg();
extern void _Nca_reg();
extern void _ntIh_reg();
extern void _ntleak_reg();
extern void _ntt_reg();
extern void _ntt_int_reg();
extern void _pasi_reg();
extern void _savedist_reg();
extern void _tia_reg();
extern void _vecstim_reg();
extern void _wrap_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," APCounter2.mod");
fprintf(stderr," ar_traub.mod");
fprintf(stderr," beforestep_py.mod");
fprintf(stderr," CA1ika.mod");
fprintf(stderr," CA1ikdr.mod");
fprintf(stderr," CA1ina.mod");
fprintf(stderr," cad.mod");
fprintf(stderr," cadad.mod");
fprintf(stderr," cadecay_destexhe.mod");
fprintf(stderr," cadyn.mod");
fprintf(stderr," Cadynamics.mod");
fprintf(stderr," cagk.mod");
fprintf(stderr," cal_mh.mod");
fprintf(stderr," cal_mig.mod");
fprintf(stderr," can_mig.mod");
fprintf(stderr," cancr.mod");
fprintf(stderr," canin.mod");
fprintf(stderr," caolmw.mod");
fprintf(stderr," capr.mod");
fprintf(stderr," cat_mig.mod");
fprintf(stderr," cat_traub.mod");
fprintf(stderr," catcb.mod");
fprintf(stderr," ch_CavL.mod");
fprintf(stderr," ch_CavN.mod");
fprintf(stderr," ch_KCaS.mod");
fprintf(stderr," ch_Kdrfastngf.mod");
fprintf(stderr," ch_KvAngf.mod");
fprintf(stderr," ch_KvCaB.mod");
fprintf(stderr," ch_leak.mod");
fprintf(stderr," ch_Navngf.mod");
fprintf(stderr," cp.mod");
fprintf(stderr," cp2.mod");
fprintf(stderr," DynamicNetStim.mod");
fprintf(stderr," gabab.mod");
fprintf(stderr," h_BS.mod");
fprintf(stderr," h_harnett.mod");
fprintf(stderr," h_kole.mod");
fprintf(stderr," h_migliore.mod");
fprintf(stderr," HH_traub.mod");
fprintf(stderr," HH2.mod");
fprintf(stderr," hin.mod");
fprintf(stderr," htc.mod");
fprintf(stderr," Iahp.mod");
fprintf(stderr," IC.mod");
fprintf(stderr," ICal.mod");
fprintf(stderr," Ican.mod");
fprintf(stderr," ican_sidi.mod");
fprintf(stderr," icaolmw.mod");
fprintf(stderr," icapr.mod");
fprintf(stderr," iccr.mod");
fprintf(stderr," iconc_Ca.mod");
fprintf(stderr," iholmkop.mod");
fprintf(stderr," iholmw.mod");
fprintf(stderr," ihpyrkop.mod");
fprintf(stderr," IKM.mod");
fprintf(stderr," ikscr.mod");
fprintf(stderr," IKsin.mod");
fprintf(stderr," IL.mod");
fprintf(stderr," IL_gutnick.mod");
fprintf(stderr," IM_cortex.mod");
fprintf(stderr," ipulse3.mod");
fprintf(stderr," IT.mod");
fprintf(stderr," IT2.mod");
fprintf(stderr," kahppr.mod");
fprintf(stderr," kaolmkop.mod");
fprintf(stderr," kap_BS.mod");
fprintf(stderr," kapcb.mod");
fprintf(stderr," kapin.mod");
fprintf(stderr," kapyrkop.mod");
fprintf(stderr," kBK.mod");
fprintf(stderr," kca.mod");
fprintf(stderr," kcaolmw.mod");
fprintf(stderr," kcpr.mod");
fprintf(stderr," kctin.mod");
fprintf(stderr," kdmc_BS.mod");
fprintf(stderr," kdr_BS.mod");
fprintf(stderr," kdr2_orig.mod");
fprintf(stderr," kdrbwb.mod");
fprintf(stderr," kdrcr.mod");
fprintf(stderr," kdrin.mod");
fprintf(stderr," kdrolmkop.mod");
fprintf(stderr," kdrpr.mod");
fprintf(stderr," kdrpyrkop.mod");
fprintf(stderr," kl.mod");
fprintf(stderr," km.mod");
fprintf(stderr," kv.mod");
fprintf(stderr," my_exp2syn.mod");
fprintf(stderr," MyExp2SynAlpha.mod");
fprintf(stderr," MyExp2SynBB.mod");
fprintf(stderr," MyExp2SynNMDABB.mod");
fprintf(stderr," na_2.mod");
fprintf(stderr," naf2.mod");
fprintf(stderr," nafbwb.mod");
fprintf(stderr," nafcr.mod");
fprintf(stderr," nafolmkop.mod");
fprintf(stderr," nafpr.mod");
fprintf(stderr," nafpyrkop.mod");
fprintf(stderr," nafx.mod");
fprintf(stderr," nap_sidi.mod");
fprintf(stderr," nax_BS.mod");
fprintf(stderr," naz.mod");
fprintf(stderr," Nca.mod");
fprintf(stderr," ntIh.mod");
fprintf(stderr," ntleak.mod");
fprintf(stderr," ntt.mod");
fprintf(stderr," ntt_int.mod");
fprintf(stderr," pasi.mod");
fprintf(stderr," savedist.mod");
fprintf(stderr," tia.mod");
fprintf(stderr," vecstim.mod");
fprintf(stderr," wrap.mod");
fprintf(stderr, "\n");
    }
_APCounter2_reg();
_ar_traub_reg();
_beforestep_py_reg();
_CA1ika_reg();
_CA1ikdr_reg();
_CA1ina_reg();
_cad_reg();
_cadad_reg();
_cadecay_destexhe_reg();
_cadyn_reg();
_Cadynamics_reg();
_cagk_reg();
_cal_mh_reg();
_cal_mig_reg();
_can_mig_reg();
_cancr_reg();
_canin_reg();
_caolmw_reg();
_capr_reg();
_cat_mig_reg();
_cat_traub_reg();
_catcb_reg();
_ch_CavL_reg();
_ch_CavN_reg();
_ch_KCaS_reg();
_ch_Kdrfastngf_reg();
_ch_KvAngf_reg();
_ch_KvCaB_reg();
_ch_leak_reg();
_ch_Navngf_reg();
_cp_reg();
_cp2_reg();
_DynamicNetStim_reg();
_gabab_reg();
_h_BS_reg();
_h_harnett_reg();
_h_kole_reg();
_h_migliore_reg();
_HH_traub_reg();
_HH2_reg();
_hin_reg();
_htc_reg();
_Iahp_reg();
_IC_reg();
_ICal_reg();
_Ican_reg();
_ican_sidi_reg();
_icaolmw_reg();
_icapr_reg();
_iccr_reg();
_iconc_Ca_reg();
_iholmkop_reg();
_iholmw_reg();
_ihpyrkop_reg();
_IKM_reg();
_ikscr_reg();
_IKsin_reg();
_IL_reg();
_IL_gutnick_reg();
_IM_cortex_reg();
_ipulse3_reg();
_IT_reg();
_IT2_reg();
_kahppr_reg();
_kaolmkop_reg();
_kap_BS_reg();
_kapcb_reg();
_kapin_reg();
_kapyrkop_reg();
_kBK_reg();
_kca_reg();
_kcaolmw_reg();
_kcpr_reg();
_kctin_reg();
_kdmc_BS_reg();
_kdr_BS_reg();
_kdr2_orig_reg();
_kdrbwb_reg();
_kdrcr_reg();
_kdrin_reg();
_kdrolmkop_reg();
_kdrpr_reg();
_kdrpyrkop_reg();
_kl_reg();
_km_reg();
_kv_reg();
_my_exp2syn_reg();
_MyExp2SynAlpha_reg();
_MyExp2SynBB_reg();
_MyExp2SynNMDABB_reg();
_na_2_reg();
_naf2_reg();
_nafbwb_reg();
_nafcr_reg();
_nafolmkop_reg();
_nafpr_reg();
_nafpyrkop_reg();
_nafx_reg();
_nap_sidi_reg();
_nax_BS_reg();
_naz_reg();
_Nca_reg();
_ntIh_reg();
_ntleak_reg();
_ntt_reg();
_ntt_int_reg();
_pasi_reg();
_savedist_reg();
_tia_reg();
_vecstim_reg();
_wrap_reg();
}
